name: int_movil
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Íconos y fuentes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0 

  # Firebase
  firebase_core: ^3.12.1  # Se recomienda actualizar a la última versión
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4

  

  # Manejo de estado
  provider: ^6.1.2

  # Otras utilidades
  table_calendar: ^3.0.9
  lottie: ^3.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  timezone: ^0.10.0
  flutter_pdfview: ^1.4.0
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fondo_login2.png  
    - assets/google_logo.png
    - assets/images/menu.jpg
    - assets/images/login_final.png
    - assets/pdfs/Manual_de_Instalacion_de_IoT.pdf
    - assets/pdfs/Manual_de_Uso_de_la_Aplicacion.pdf

  fonts:
    - family: Fjalla One
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
