// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW8CJOSIEpAzTzkrF_zk8rfU0PAgZZSyg',
    appId: '1:733056516086:web:07128fe58a67d00c3f11d7',
    messagingSenderId: '733056516086',
    projectId: 'int-movil',
    authDomain: 'int-movil.firebaseapp.com',
    storageBucket: 'int-movil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZe47WOfaM-9wv7VttWX_VH82K2mV3Bg',
    appId: '1:733056516086:android:67f2e611230c7c5d3f11d7',
    messagingSenderId: '733056516086',
    projectId: 'int-movil',
    storageBucket: 'int-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD29fhulb__n-yFJqIDUYbyyg8TWQZGnA8',
    appId: '1:733056516086:ios:a6bda028e4b5aa1f3f11d7',
    messagingSenderId: '733056516086',
    projectId: 'int-movil',
    storageBucket: 'int-movil.firebasestorage.app',
    androidClientId: '733056516086-4qbnen30bjb43o8o17djp460qkj1qjia.apps.googleusercontent.com',
    iosClientId: '733056516086-2i4mast64vgv42htrusl5hf8oui2g6nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.intMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD29fhulb__n-yFJqIDUYbyyg8TWQZGnA8',
    appId: '1:733056516086:ios:a6bda028e4b5aa1f3f11d7',
    messagingSenderId: '733056516086',
    projectId: 'int-movil',
    storageBucket: 'int-movil.firebasestorage.app',
    androidClientId: '733056516086-4qbnen30bjb43o8o17djp460qkj1qjia.apps.googleusercontent.com',
    iosClientId: '733056516086-2i4mast64vgv42htrusl5hf8oui2g6nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.intMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW8CJOSIEpAzTzkrF_zk8rfU0PAgZZSyg',
    appId: '1:733056516086:web:07957f7b203ac4b93f11d7',
    messagingSenderId: '733056516086',
    projectId: 'int-movil',
    authDomain: 'int-movil.firebaseapp.com',
    storageBucket: 'int-movil.firebasestorage.app',
  );
}
